# Generated by Django 4.1.3 on 2022-11-30 13:37

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('usuario', '0001_initial'),
        ('produto', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pedido',
            fields=[
                ('ativo', models.BooleanField(default=True, verbose_name='Ativo')),
                ('data_criacao', models.DateField(auto_now_add=True, verbose_name='Data de criação')),
                ('data_modificacao', models.DateField(auto_now=True, verbose_name='Data de modificação')),
                ('numero_pedido', models.CharField(default=uuid.uuid4, editable=False, max_length=100, primary_key=True, serialize=False, verbose_name='Número do pedido')),
                ('status_pedido', models.IntegerField(choices=[(1, 'Iniciado'), (2, 'Cancelado'), (3, 'Faturado'), (4, 'Concluído')], verbose_name='Status do pedido')),
                ('preco_pedido', models.DecimalField(decimal_places=2, max_digits=8, verbose_name='Preço do pedido')),
                ('fk_UUID_usuario', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='usuario.usuario', verbose_name='ID do usuário')),
            ],
            options={
                'verbose_name': 'Pedido',
                'verbose_name_plural': 'Pedidos',
            },
        ),
        migrations.CreateModel(
            name='PedidoProduto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ativo', models.BooleanField(default=True, verbose_name='Ativo')),
                ('data_criacao', models.DateField(auto_now_add=True, verbose_name='Data de criação')),
                ('data_modificacao', models.DateField(auto_now=True, verbose_name='Data de modificação')),
                ('preco_produto', models.DecimalField(decimal_places=2, max_digits=9, verbose_name='Preço do produto')),
                ('quantidade', models.IntegerField(verbose_name='Quantidade')),
                ('fk_id_produto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='produto.produto', verbose_name='Id do produto')),
                ('fk_numero_pedido', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pedido.pedido', verbose_name='Numero do pedido')),
            ],
            options={
                'verbose_name': 'Produto',
                'verbose_name_plural': 'Carrinho de compras',
            },
        ),
    ]
