# Generated by Django 4.1.3 on 2022-11-30 17:53

from django.db import migrations, models
import django.db.models.deletion
import pedido.validators
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('usuario', '0002_usuario_refresh_token'),
        ('pedido', '0002_alter_pedido_numero_pedido'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pedido',
            name='fk_UUID_usuario',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='usuario.usuario', validators=[pedido.validators.valida_status], verbose_name='ID do usuário'),
        ),
        migrations.AlterField(
            model_name='pedido',
            name='numero_pedido',
            field=models.CharField(default=uuid.uuid4, editable=False, max_length=100, primary_key=True, serialize=False, verbose_name='Número do pedido'),
        ),
    ]
