# Generated by Django 4.1.3 on 2022-11-30 17:53

from django.db import migrations, models
import django.db.models.deletion
import pedido.validators


class Migration(migrations.Migration):

    dependencies = [
        ('usuario', '0002_usuario_refresh_token'),
        ('pedido', '0003_alter_pedido_fk_uuid_usuario_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pedido',
            name='fk_UUID_usuario',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='usuario.usuario', verbose_name='ID do usuário'),
        ),
        migrations.AlterField(
            model_name='pedido',
            name='status_pedido',
            field=models.IntegerField(choices=[(1, 'Iniciado'), (2, 'Cancelado'), (3, 'Faturado'), (4, 'Concluído')], validators=[pedido.validators.valida_status], verbose_name='Status do pedido'),
        ),
    ]
