# Generated by Django 4.1.3 on 2022-11-30 18:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('usuario', '0002_usuario_refresh_token'),
        ('pedido', '0004_alter_pedido_fk_uuid_usuario_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pedido',
            name='fk_UUID_usuario',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='usuario.usuario', verbose_name='Usuário'),
        ),
    ]
