# Generated by Django 4.1.3 on 2022-11-30 13:37

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Produto',
            fields=[
                ('ativo', models.BooleanField(default=True, verbose_name='Ativo')),
                ('data_criacao', models.DateField(auto_now_add=True, verbose_name='Data de criação')),
                ('data_modificacao', models.DateField(auto_now=True, verbose_name='Data de modificação')),
                ('id_produto', models.CharField(default=uuid.uuid4, editable=False, max_length=100, primary_key=True, serialize=False, unique=True)),
                ('nome', models.CharField(max_length=100, verbose_name='Nome')),
                ('preco', models.DecimalField(decimal_places=2, max_digits=8, verbose_name='Preço')),
                ('preco_atual', models.DecimalField(decimal_places=2, max_digits=8, verbose_name='Preço atual')),
                ('promocao', models.BooleanField(verbose_name='Está na promoção?')),
            ],
            options={
                'verbose_name': 'Produto',
                'verbose_name_plural': 'Produtos',
            },
        ),
    ]
