# Generated by Django 4.1.3 on 2022-11-30 18:31

from django.db import migrations, models
import pedido.validators


class Migration(migrations.Migration):

    dependencies = [
        ('produto', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='produto',
            name='preco',
            field=models.DecimalField(decimal_places=2, max_digits=8, validators=[pedido.validators.convert_to_cents], verbose_name='Preço'),
        ),
        migrations.AlterField(
            model_name='produto',
            name='preco_atual',
            field=models.DecimalField(decimal_places=2, max_digits=8, validators=[pedido.validators.convert_to_cents], verbose_name='Preço atual'),
        ),
    ]
