# Generated by Django 4.1.3 on 2022-11-16 17:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produto', '0002_alter_produto_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='produto',
            name='id_produto',
            field=models.CharField(default='XXX-0000', editable=False, max_length=100, primary_key=True, serialize=False, unique=True, verbose_name='Id Produto'),
        ),
    ]
