# Generated by Django 4.1.3 on 2022-11-09 17:00

import django.core.validators
from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('ativo', models.BooleanField(default=True, verbose_name='Ativo')),
                ('data_criacao', models.DateField(auto_now_add=True, verbose_name='Data de criação')),
                ('data_modificacao', models.DateField(auto_now=True, verbose_name='Data de modificação')),
                ('id_usuario', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('nome', models.CharField(max_length=100, verbose_name='Nome')),
                ('email', models.EmailField(max_length=254, verbose_name='E-mail')),
                ('senha', models.CharField(max_length=100, validators=[django.core.validators.MinLengthValidator(8)], verbose_name='Senha')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
