# Generated by Django 4.1.3 on 2022-11-10 17:01

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuario', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='senha',
            field=models.CharField(help_text='Password: \nmust be longer than 8 digits\nmust have at least one number\npassword must have at least 1 special digit\npassword must have at least 1 upper digit', max_length=100, validators=[django.core.validators.MinLengthValidator(8)], verbose_name='Senha'),
        ),
    ]
