# Generated by Django 4.1.3 on 2022-11-22 21:01

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('usuario', '0008_alter_usuario_id_usuario'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='hashed_password',
            field=models.CharField(default=None, max_length=100, verbose_name='Senha'),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='id_usuario',
            field=models.CharField(default=uuid.uuid4, editable=False, max_length=36, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='sobrenome',
            field=models.CharField(default=None, max_length=100, unique=True, verbose_name='Sobrenome'),
        ),
    ]
