# Generated by Django 4.1.3 on 2022-11-09 17:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('usuario', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pedido',
            fields=[
                ('ativo', models.BooleanField(default=True, verbose_name='Ativo')),
                ('data_criacao', models.DateField(auto_now_add=True, verbose_name='Data de criação')),
                ('data_modificacao', models.DateField(auto_now=True, verbose_name='Data de modificação')),
                ('numero_pedido', models.BigAutoField(primary_key=True, serialize=False, verbose_name='Número do pedido')),
                ('status_pedido', models.IntegerField(choices=[(1, 'Iniciado'), (2, 'Cancelado'), (3, 'Faturado'), (4, 'Concluído')], verbose_name='Status do pedido')),
                ('preco_pedido', models.DecimalField(decimal_places=2, max_digits=8, verbose_name='Preço do pedido')),
                ('fk_UUID_usuario', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='usuario.usuario', verbose_name='ID do usuário')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
