# Generated by Django 4.1.3 on 2022-11-09 17:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('produto', '0002_alter_produto_options'),
        ('pedido', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PedidoProduto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ativo', models.BooleanField(default=True, verbose_name='Ativo')),
                ('data_criacao', models.DateField(auto_now_add=True, verbose_name='Data de criação')),
                ('data_modificacao', models.DateField(auto_now=True, verbose_name='Data de modificação')),
                ('preco_produto', models.DecimalField(decimal_places=2, max_digits=8, verbose_name='Preço do produto')),
                ('quantidade', models.IntegerField(verbose_name='Quantidade')),
                ('fk_id_produto', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='produto.produto', verbose_name='Id do produto')),
                ('fk_numero_pedido', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='pedido.pedido', verbose_name='Numero do pedido')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
