# Generated by Django 4.1.3 on 2022-11-10 17:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pedido', '0002_pedidoproduto'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='pedido',
            options={'verbose_name': 'Pedido', 'verbose_name_plural': 'Pedidos'},
        ),
        migrations.AlterModelOptions(
            name='pedidoproduto',
            options={'verbose_name': 'Carrinho de compra', 'verbose_name_plural': 'Carrinhos de compra'},
        ),
    ]
