# Generated by Django 4.1.3 on 2022-11-10 17:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pedido', '0003_alter_pedido_options_alter_pedidoproduto_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pedido',
            name='numero_pedido',
            field=models.CharField(max_length=100, primary_key=True, serialize=False, unique=True, verbose_name='Número do pedido'),
        ),
    ]
