# Generated by Django 4.1.3 on 2022-11-11 17:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pedido', '0004_alter_pedido_numero_pedido'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='pedidoproduto',
            options={'verbose_name': 'Carrinho de compra', 'verbose_name_plural': 'Carrinho de compras'},
        ),
    ]
