# Generated by Django 4.1.3 on 2022-11-14 19:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('produto', '0002_alter_produto_options'),
        ('pedido', '0005_alter_pedidoproduto_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='pedidoproduto',
            options={'verbose_name': 'Produto', 'verbose_name_plural': 'Carrinho de compras'},
        ),
        migrations.AlterField(
            model_name='pedido',
            name='numero_pedido',
            field=models.CharField(help_text='Padrão: AAA-0000', max_length=100, primary_key=True, serialize=False, unique=True, verbose_name='Número do pedido'),
        ),
        migrations.AlterField(
            model_name='pedidoproduto',
            name='fk_id_produto',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='produto.produto', verbose_name='Id do produto'),
        ),
        migrations.AlterField(
            model_name='pedidoproduto',
            name='fk_numero_pedido',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pedido.pedido', verbose_name='Numero do pedido'),
        ),
    ]
