# Generated by Django 4.1.3 on 2022-11-14 19:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('usuario', '0005_alter_usuario_options_alter_usuario_id_usuario'),
        ('pedido', '0006_alter_pedidoproduto_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pedido',
            name='fk_UUID_usuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='usuario.usuario', verbose_name='ID do usuário'),
        ),
    ]
