# Generated by Django 4.1.3 on 2022-11-23 13:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('usuario', '0009_alter_usuario_hashed_password_and_more'),
        ('pedido', '0007_alter_pedido_fk_uuid_usuario'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pedido',
            name='fk_UUID_usuario',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='usuario.usuario', verbose_name='ID do usuário'),
        ),
    ]
