# Generated by Django 4.1.3 on 2022-11-23 17:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pedido', '0008_alter_pedido_fk_uuid_usuario'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pedidoproduto',
            name='preco_produto',
            field=models.DecimalField(decimal_places=2, max_digits=9, verbose_name='Preço do produto'),
        ),
    ]
