# Generated by Django 4.1.3 on 2022-11-23 17:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('produto', '0006_alter_produto_id_produto'),
        ('pedido', '0009_alter_pedidoproduto_preco_produto'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='PedidoProduto',
            new_name='PedidoeProduto',
        ),
    ]
