# Generated by Django 4.1.3 on 2022-11-23 17:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('produto', '0006_alter_produto_id_produto'),
        ('pedido', '0010_rename_pedidoproduto_pedidoeproduto'),
    ]

    operations = [
        migrations.CreateModel(
            name='PedidoProdutos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ativo', models.BooleanField(default=True, verbose_name='Ativo')),
                ('data_criacao', models.DateField(auto_now_add=True, verbose_name='Data de criação')),
                ('data_modificacao', models.DateField(auto_now=True, verbose_name='Data de modificação')),
                ('preco_produto', models.DecimalField(decimal_places=2, max_digits=9, verbose_name='Preço do produto')),
                ('quantidade', models.IntegerField(verbose_name='Quantidade')),
                ('fk_id_produto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='produto.produto', verbose_name='Id do produto')),
                ('fk_numero_pedido', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pedido.pedido', verbose_name='Numero do pedido')),
            ],
            options={
                'verbose_name': 'Produto',
                'verbose_name_plural': 'Carrinho de compras',
            },
        ),
        migrations.DeleteModel(
            name='PedidoeProduto',
        ),
    ]
