# Generated by Django 4.1.3 on 2022-11-30 16:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuario', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='refresh_token',
            field=models.CharField(max_length=300, null=True, unique=True, verbose_name='refresh token'),
        ),
    ]
